export type { ProgrammeParams } from './programme';
export { Programme } from './programme';
export { ProgrammeComponent } from './programmeComponent';
export { formatFilterConfigData } from './formatFilterConfigData';
export type { FilterConfigData } from './types';
export * from './filterItems';
export { NormalProgramme } from './normalProgramme/normalProgramme';
export { NormalProgrammeComponent } from './normalProgramme/normalProgrammeComponent';
export type { NormalProgrammeParams } from './normalProgramme/normalProgramme';
export * from './tabsProgramme';
